<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://accessibility.java.sun.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://accessibility.java.sun.com" xmlns:intf="http://accessibility.java.sun.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="_AccessibleState">

   </wsdl:portType>

   <wsdl:binding name="_AccessibleStateSoapBinding" type="impl:_AccessibleState">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="_AccessibleStateService">

      <wsdl:port binding="impl:_AccessibleStateSoapBinding" name="_AccessibleState">

         <wsdlsoap:address location="http://localhost:8081/jaxrs-jersy/services/_AccessibleState"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
